#!/usr/local/bin/php -q
<?php
require "core/Setup.php";
require "util/Debug.php";
require "util/File.php";
require "util/Image.php";

use core\Setup;
use util\Debug;

switch(count($argv)){
	default:Debug::error("사용법: setup /home/sample/source/sample.bml");
	case 2:new Setup($argv[1]);;break;
}
?>